---
spring:
  profiles: service1
  application:
    name: eureka-high-avai-service
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/

---
spring:
  profiles: service2
  application:
    name: eureka-high-avai-service
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/